dijet_selection:
  name: DijetSelection
  path: modules.dijet_selection
  parameters:
    year: self.config.year

bdt_inference:
  name: L1DSBDT
  path: L1DS.Modules.BDTinference
  parameters:
    year: self.config.year
    isMC: self.dataset.process.isMC